=== RichieSams/lantern/scenes/scene.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Lantern Scene Definition Schema",
	"type": "object",
	"required": [ "camera" ],
	"properties": {
		"background_color": {
			"description": "",
			"$ref": "#/definitions/float3"
		},
		"camera": {
			"description": "",
			"type": "object",
			"required": [ "position", "target", "up", "client_width", "client_height" ],
			"properties": {
				"position": {
					"description": "",
					"$ref": "#/definitions/float3"
				},
				"target": {
					"description": "",
					"$ref": "#/definitions/float3"
				},
				"up": {
					"description": "",
					"$ref": "#/definitions/float3"
				},
				"client_width": {
					"description": "",
					"type": "number"
				},
				"client_height": {
					"description": "",
					"type": "number"
				},
				"fov": {
					"description": "",
					"type": "number"
				}
			}
		},
		"materials": {
			"description": "",
			"type": "array",
			"items": {
				"oneOf": [
					{ "$ref": "#/definitions/matte_material" }
				]
			}
		},
		"media": {
			"description": "",
			"type": "array",
			"items": {
				"oneOf": [
					{ "$ref": "#/definitions/non_scattering_medium" },
					{ "$ref": "#/definitions/isotropic_scattering_medium" }
				]
			}
		},
		"primitives": {
			"description": "",
			"type": "array",
			"items": {
				"oneOf": [
					{ "$ref": "#/definitions/lantern_model_file" },
					{ "$ref": "#/definitions/grid" },
					{ "$ref": "#/definitions/sphere" }
				]
			}
		}
	},
	"additionalProperties": false,
	"definitions": {
		"float2": {
			"type": "array",
			"items": {
				"type": "number"
			},
			"minItems": 2,
			"maxItems": 2,
			"additionalItems": false
		},
		"float3": {
			"type": "array",
			"items": {
				"type": "number"
			},
			"minItems": 3,
			"maxItems": 3,
			"additionalItems": false
		},
		"float4x4": {
			"type": "array",
			"items": {
				"type": "number"
			},
			"minItems": 16,
			"maxItems": 16,
			"additionalItems": false
		},

		"constant_texture": {
			"type": "object",
			"required": [ "type" ],
			"properties": {
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "constant" ]
				},
				"value": {
					"description": "",
					"$ref": "#/definitions/float3"
				}
			}
		},
		"image_texture": {
			"type": "object",
			"required": [ "type" ],
			"properties": {
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "image" ]
				},
				"file_path": {
					"description": "",
					"type": "string"
				}
			}
		},
		"uv_texture": {
			"type": "object",
			"required": [ "type" ],
			"properties": {
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "uv" ]
				}
			}
		},

		"matte_material": {
			"type": "object",
			"required": [ "name", "type", "albedo" ],
			"properties": {
				"name": {
					"description": "",
					"type": "string"
				},
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "matte" ]
				},
				"albedo": {
					"description": "",
					"oneOf": [
						{ "$ref": "#/definitions/constant_texture" },
						{ "$ref": "#/definitions/image_texture" },
						{ "$ref": "#/definitions/uv_texture" }
					]
				}
			}
		},

		"non_scattering_medium": {
			"type": "object",
			"required": [ "name", "type", "absorption_color", "absorption_at_distance" ],
			"properties": {
				"name": {
					"description": "",
					"type": "string"
				},
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "non_scattering" ]
				},
				"absorption_color": {
					"description": "",
					"$ref": "#/definitions/float3"
				},
				"absorption_at_distance": {
					"description": "",
					"type": "number"
				}
			}
		},
		"isotropic_scattering_medium": {
			"type": "object",
			"required": [ "name", "type", "absorption_color", "absorption_at_distance", "scattering_distance" ],
			"properties": {
				"name": {
					"description": "",
					"type": "string"
				},
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "isotropic_scattering" ]
				},
				"absorption_color": {
					"description": "",
					"$ref": "#/definitions/float3"
				},
				"absorption_at_distance": {
					"description": "",
					"type": "number"
				},
				"scattering_distance": {
					"description": "",
					"type": "number"
				}
			}
		},

		"lantern_model_file": {
			"type": "object",
			"required": [ "name", "type", "file_path", "material" ],
			"properties": {
				"name": {
					"description": "",
					"type": "string"
				},
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "lmf" ]
				},
				"file_path": {
					"description": "",
					"type": "string"
				},
				"material": {
					"description": "",
					"type": "string"
				},
				"medium": {
					"description": "",
					"type": "string"
				},
				"transform": {
					"description": "",
					"$ref": "#/definitions/float4x4"
				},
				"emission": {
					"description": "",
					"type": "object",
					"required": [ "color", "radiant_power" ],
					"properties": {
						"color": {
							"description": "",
							"$ref": "#/definitions/float3"
						},
						"radiant_power": {
							"description": "",
							"type": "number"
						}
					}
				}
			}
		},
		"grid": {
			"type": "object",
			"required": [ "name", "type", "width", "depth", "material" ],
			"properties": {
				"name": {
					"description": "",
					"type": "string"
				},
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "grid" ]
				},
				"width": {
					"description": "",
					"type": "number"
				},
				"depth": {
					"description": "",
					"type": "number"
				},
				"material": {
					"description": "",
					"type": "string"
				},
				"medium": {
					"description": "",
					"type": "string"
				},
				"transform": {
					"description": "",
					"$ref": "#/definitions/float4x4"
				},
				"emission": {
					"description": "",
					"type": "object",
					"required": [ "color", "radiant_power" ],
					"properties": {
						"color": {
							"description": "",
							"$ref": "#/definitions/float3"
						},
						"radiant_power": {
							"description": "",
							"type": "number"
						}
					}
				}
			}
		},
		"sphere": {
			"type": "object",
			"required": [ "name", "type", "radius", "material" ],
			"properties": {
				"name": {
					"description": "",
					"type": "string"
				},
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "sphere" ]
				},
				"radius": {
					"description": "",
					"type": "number"
				},
				"material": {
					"description": "",
					"type": "string"
				},
				"medium": {
					"description": "",
					"type": "string"
				},
				"transform": {
					"description": "",
					"$ref": "#/definitions/float4x4"
				},
				"emission": {
					"description": "",
					"type": "object",
					"required": [ "color", "radiant_power" ],
					"properties": {
						"color": {
							"description": "",
							"$ref": "#/definitions/float3"
						},
						"radiant_power": {
							"description": "",
							"type": "number"
						}
					}
				}
			}
		}
	}
}

=== RichieSams/lantern/scenes/nine_balls_scene.json
{
	"background_color": [ 0.846, 0.933, 0.949 ],
	"camera": {
		"position": [ 0.0, 0.0, 40.0 ],
		"target": [ 0.0, 0.0, 0.0 ],
		"up": [ 0.0, 1.0, 0.0 ],
		"client_width": 1280,
		"client_height": 720,
		"fov": 0.7853981
	},
	"materials": [
		{
			"name": "green",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 0.408, 0.741, 0.467 ]
			}
		},
		{
			"name": "blue",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 0.392, 0.584, 0.929 ]
			}
		},
		{
			"name": "orange",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 1.0, 0.498, 0.314 ]
			}
		},
		{
			"name": "black",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 0.0, 0.0, 0.0 ]
			}
		},
		{
			"name": "gray",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 0.9, 0.9, 0.9 ]
			}
		},
		{
			"name": "glass",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 0.9, 0.9, 0.9 ]
			}
		},
    {
      "name": "mirror",
      "type": "matte",
      "albedo": {
        "type": "constant",
        "value": [ 0.9, 0.9, 0.9 ]
      }
    }
	],
	"primitives": [
		{
			"name": "floor",
			"type": "grid",
			"width": 10.0,
			"depth": 10.0,
			"n": 2,
			"m": 2,
			"material": "gray",
			"transform": [
				1, 0, 0,  0,
				0, 1, 0, -6,
				0, 0, 1,  0,
				0, 0, 0,  1
			]
		},
	  {
			"name": "ceiling",
			"type": "grid",
			"width": 10.0,
			"depth": 10.0,
			"n": 2,
			"m": 2,
			"material": "gray",
			"transform": [
				1, 0, 0, 0,
				0, 1, 0, 6,
				0, 0, 1, 0,
				0, 0, 0, 1
			]
		},
    {
			"name": "right",
			"type": "grid",
			"width": 10.0,
			"depth": 10.0,
			"n": 2,
			"m": 2,
			"material": "gray",
			"transform": [
				0.0, -1.0, 0.0, 6.0,
				1.0,  0.0, 0.0, 0.0,
				0.0,  0.0, 1.0, 0.0,
				0.0,  0.0, 0.0, 1.0
      ]
		},
		{
			"name": "left",
			"type": "grid",
			"width": 10.0,
			"depth": 10.0,
			"n": 2,
			"m": 2,
			"material": "gray",
			"transform": [
				 0.0, 1.0, 0.0, -6.0,
				-1.0, 0.0, 0.0,  0.0,
				 0.0, 0.0, 1.0,  0.0,
         0.0, 0.0, 0.0,  1.0
      ]
    },
    {
      "name": "far_left",
      "type": "grid",
      "width": 10.0,
      "depth": 10.0,
      "n": 2,
      "m": 2,
      "material": "gray",
      "transform": [
				0.0, -1.0, 0.0, -11.0,
				1.0,  0.0, 0.0,   0.0,
				0.0,  0.0, 1.0,   0.0,
				6.0,  0.0, 0.0,   1.0
      ]
    }
  ]
}

=== RichieSams/lantern/scenes/bitterli_dragon_scene.json
{
	"background_color": [ 0.846, 0.933, 0.949 ],
	"camera": {
		"position": [
			58.20600128173828,
			24.92840003967285,
			52.950096130371094
		],
		"target": [
			-1.505810022354126,
			5.869430065155029,
			-2.1437699794769287
		],
		"up": [ 0.0, 1.0, 0.0 ],
		"client_width": 1280,
		"client_height": 720,
		"fov": 0.7853981
	},
	"materials": [
		{
			"name": "GroundInner",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 0.456263, 0.456263, 0.456263 ]
			}
		},
		{
			"name": "GroundOuter",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 0.456263, 0.456263, 0.456263 ]
			}
		},
		{
			"name": "Cloth",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 0.456263, 0.456263, 0.456263 ]
			}
		},
		{
			"name": "Dragon",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 0.79311, 0.79311, 0.79311 ]
			}
		},
		{
			"name": "Blade",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 0.79311, 0.79311, 0.79311 ]
			}
		},
		{
			"name": "Sword",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 0.79311, 0.79311, 0.79311 ]
			}
		},
		{
			"name": "Deco",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 0.79311, 0.79311, 0.79311 ]
			}
		},
		{
			"name": "Diamond",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 0.79311, 0.79311, 0.79311 ]
			}
		},
		{
			"name": "Deco2",
			"type": "matte",
			"albedo": {
				"type": "constant",
				"value": [ 0.79311, 0.79311, 0.79311 ]
			}
		}
	],
	"media": [],
	"primitives": [
		{
			"name": "GroundOuter",
			"type": "lmf",
			"file_path": "models/Mesh011.lmf",
			"material": "GroundOuter"
		},
		{
			"name": "Cloth",
			"type": "lmf",
			"file_path": "models/Mesh010.lmf",
			"material": "Cloth"
		},
		{
			"name": "GroundOuter",
			"type": "lmf",
			"file_path": "models/Mesh005.lmf",
			"material": "GroundOuter"
		},
		{
			"name": "GroundOuter",
			"type": "lmf",
			"file_path": "models/Mesh006.lmf",
			"material": "GroundOuter"
		},
		{
			"name": "GroundInner",
			"type": "lmf",
			"file_path": "models/Mesh012.lmf",
			"material": "GroundInner"
		},
		{
			"name": "GroundOuter",
			"type": "lmf",
			"file_path": "models/Mesh007.lmf",
			"material": "GroundOuter"
		},
		{
			"name": "Dragon",
			"type": "lmf",
			"file_path": "models/Mesh008.lmf",
			"material": "Dragon"
		},
		{
			"name": "Dragon",
			"type": "lmf",
			"file_path": "models/Mesh013.lmf",
			"material": "Dragon"
		},
		{
			"name": "Dragon",
			"type": "lmf",
			"file_path": "models/Mesh014.lmf",
			"material": "Dragon"
		},
		{
			"name": "Dragon",
			"type": "lmf",
			"file_path": "models/Mesh015.lmf",
			"material": "Dragon"
		},
		{
			"name": "Blade",
			"type": "lmf",
			"file_path": "models/Mesh004.lmf",
			"material": "Blade"
		},
		{
			"name": "Sword",
			"type": "lmf",
			"file_path": "models/Mesh009.lmf",
			"material": "Sword"
		},
		{
			"name": "Deco",
			"type": "lmf",
			"file_path": "models/Mesh003.lmf",
			"material": "Deco"
		},
		{
			"name": "Diamond",
			"type": "lmf",
			"file_path": "models/Mesh002.lmf",
			"material": "Diamond"
		},
		{
			"name": "Deco2",
			"type": "lmf",
			"file_path": "models/Mesh001.lmf",
			"material": "Deco2"
		},
		{
			"name": "Deco2",
			"type": "lmf",
			"file_path": "models/Mesh000.lmf",
			"material": "Deco2"
		}
	]
}
