=== RichieSams/lantern/documentation/file_formats/lantern_model_file/scene.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Lantern Scene Definition Schema",
	"type": "object",
	"required": [ "camera" ],
	"properties": {
		"background_color": {
			"description": "",
			"$ref": "#/definitions/float3"
		},
		"camera": {
			"description": "",
			"type": "object",
			"required": [ "client_width", "client_height" ],
			"properties": {
				"phi": {
					"description": "",
					"type": "number"
				},
				"theta": {
					"description": "",
					"type": "number"
				},
				"radius": {
					"description": "",
					"type": "number"
				},
				"client_width": {
					"description": "",
					"type": "number"
				},
				"client_height": {
					"description": "",
					"type": "number"
				},
				"fov": {
					"description": "",
					"type": "number"
				},
				"target": {
					"description": "",
					"$ref": "#/definitions/float3"
				}
			}
		},
		"bsdfs": {
			"description": "",
			"type": "array",
			"items": {
				"oneOf": [
					{ "$ref": "#/definitions/ideal_specular_dielectric_bsdf" },
					{ "$ref": "#/definitions/lambert_bsdf" },
					{ "$ref": "#/definitions/mirror_bsdf" }
				]
			}
		},
		"media": {
			"description": "",
			"type": "array",
			"items": {
				"oneOf": [
					{ "$ref": "#/definitions/non_scattering_medium" },
					{ "$ref": "#/definitions/isotropic_scattering_medium" }
				]
			}
		},
		"materials": {
			"description": "",
			"type": "array",
			"items": {
				"type": "object",
				"required": [ "bsdf" ],
				"properties": {
					"name": {
						"description": "",
						"type": "string"
					},
					"bsdf": {
						"description": "",
						"type": "string"
					},
					"medium": {
						"description": "",
						"type": "string"
					}
				}
			}
		},
		"primitives": {
			"description": "",
			"type": "array",
			"items": {
				"oneOf": [
					{ "$ref": "#/definitions/lantern_model_file" },
					{ "$ref": "#/definitions/grid" },
					{ "$ref": "#/definitions/geosphere" }
				]
			}
		}
	},
	"additionalProperties": false,
	"definitions": {
		"float2": {
			"type": "array",
			"items": {
				"type": "number"
			},
			"minItems": 2,
			"maxItems": 2,
			"additionalItems": false
		},
		"float3": {
			"type": "array",
			"items": {
				"type": "number"
			},
			"minItems": 3,
			"maxItems": 3,
			"additionalItems": false
		},
		"float4x4": {
			"type": "array",
			"items": {
				"type": "number"
			},
			"minItems": 16,
			"maxItems": 16,
			"additionalItems": false
		},

		"constant_texture": {
			"type": "object",
			"required": [ "type" ],
			"properties": {
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "constant" ]
				},
				"value": {
					"description": "",
					"$ref": "#/definitions/float3"
				}
			}
		},
		"image_texture": {
			"type": "object",
			"required": [ "type" ],
			"properties": {
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "image" ]
				},
				"file_path": {
					"description": "",
					"type": "string"
				}
			}
		},
		"uv_texture": {
			"type": "object",
			"required": [ "type" ],
			"properties": {
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "uv" ]
				}
			}
		},

		"ideal_specular_dielectric_bsdf": {
			"type": "object",
			"required": [ "name", "type", "albedo", "ior" ],
			"properties": {
				"name": {
					"description": "",
					"type": "string"
				},
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "ideal_specular_dielectric" ]
				},
				"albedo": {
					"description": "",
					"oneOf": [
						{ "$ref": "#/definitions/constant_texture" },
						{ "$ref": "#/definitions/image_texture" },
						{ "$ref": "#/definitions/uv_texture" }
					]
				},
				"ior": {
					"description": "",
					"type": "number"
				}
			}
		},
		"lambert_bsdf": {
			"type": "object",
			"required": [ "name", "type", "albedo" ],
			"properties": {
				"name": {
					"description": "",
					"type": "string"
				},
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "lambert" ]
				},
				"albedo": {
					"description": "",
					"oneOf": [
						{ "$ref": "#/definitions/constant_texture" },
						{ "$ref": "#/definitions/image_texture" },
						{ "$ref": "#/definitions/uv_texture" }
					]
				}
			}
		},
		"mirror_bsdf": {
			"type": "object",
			"required": [ "name", "type", "albedo" ],
			"properties": {
				"name": {
					"description": "",
					"type": "string"
				},
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "mirror" ]
				},
				"albedo": {
					"description": "",
					"oneOf": [
						{ "$ref": "#/definitions/constant_texture" },
						{ "$ref": "#/definitions/image_texture" },
						{ "$ref": "#/definitions/uv_texture" }
					]
				}
			}
		},

		"non_scattering_medium": {
			"type": "object",
			"required": [ "name", "type", "absorption_color", "absorption_at_distance" ],
			"properties": {
				"name": {
					"description": "",
					"type": "string"
				},
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "non_scattering" ]
				},
				"absorption_color": {
					"description": "",
					"$ref": "#/definitions/float3"
				},
				"absorption_at_distance": {
					"description": "",
					"type": "number"
				}
			}
		},
		"isotropic_scattering_medium": {
			"type": "object",
			"required": [ "name", "type", "absorption_color", "absorption_at_distance", "scattering_distance" ],
			"properties": {
				"name": {
					"description": "",
					"type": "string"
				},
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "isotropic_scattering" ]
				},
				"absorption_color": {
					"description": "",
					"$ref": "#/definitions/float3"
				},
				"absorption_at_distance": {
					"description": "",
					"type": "number"
				},
				"scattering_distance": {
					"description": "",
					"type": "number"
				}
			}
		},

		"lantern_model_file": {
			"type": "object",
			"required": [ "name", "type", "file_path", "material" ],
			"properties": {
				"name": {
					"description": "",
					"type": "string"
				},
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "lmf" ]
				},
				"file_path": {
					"description": "",
					"type": "string"
				},
				"material": {
					"description": "",
					"type": "string"
				},
				"transform": {
					"description": "",
					"$ref": "#/definitions/float4x4"
				},
				"emission": {
					"description": "",
					"type": "object",
					"required": [ "color", "radiant_power" ],
					"properties": {
						"color": {
							"description": "",
							"$ref": "#/definitions/float3"
						},
						"radiant_power": {
							"description": "",
							"type": "number"
						}
					}
				}
			}
		},
		"grid": {
			"type": "object",
			"required": [ "name", "type", "width", "depth", "material" ],
			"properties": {
				"name": {
					"description": "",
					"type": "string"
				},
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "grid" ]
				},
				"width": {
					"description": "",
					"type": "number"
				},
				"depth": {
					"description": "",
					"type": "number"
				},
				"n": {
					"description": "Number of divisons in X",
					"type": "number"
				},
				"m": {
					"description": "Number of divison in Z",
					"type": "number"
				},
				"material": {
					"description": "",
					"type": "string"
				},
				"transform": {
					"description": "",
					"$ref": "#/definitions/float4x4"
				},
				"emission": {
					"description": "",
					"type": "object",
					"required": [ "color", "radiant_power" ],
					"properties": {
						"color": {
							"description": "",
							"$ref": "#/definitions/float3"
						},
						"radiant_power": {
							"description": "",
							"type": "number"
						}
					}
				}
			}
		},
		"geosphere": {
			"type": "object",
			"required": [ "name", "type", "radius", "n", "material" ],
			"properties": {
				"name": {
					"description": "",
					"type": "string"
				},
				"type": {
					"description": "",
					"type": "string",
					"enum": [ "geosphere" ]
				},
				"radius": {
					"description": "",
					"type": "number"
				},
				"n": {
					"description": "Number of  subdivisions",
					"type": "number"
				},
				"material": {
					"description": "",
					"type": "string"
				},
				"transform": {
					"description": "",
					"$ref": "#/definitions/float4x4"
				},
				"emission": {
					"description": "",
					"type": "object",
					"required": [ "color", "radiant_power" ],
					"properties": {
						"color": {
							"description": "",
							"$ref": "#/definitions/float3"
						},
						"radiant_power": {
							"description": "",
							"type": "number"
						}
					}
				}
			}
		}
	}
}

=== RichieSams/lantern/scenes/stanford_dragon_scene.json
{
	"background_color": [ 0.846, 0.933, 0.949 ],
	"camera": {
		"position": [ -2.0, 1.0, 0.0 ],
		"target": [ 0.0, 0.0, 0.0 ],
		"up": [ 0.0, 1.0, 0.0 ],
		"client_width": 1280,
		"client_height": 720,
		"fov": 0.7853981
	},
	"bsdfs": [
		{
			"name": "glass",
			"type": "ideal_specular_dielectric",
			"albedo": {
				"type": "constant",
				"value": [ 1.0, 1.0, 1.0 ]
			},
			"ior": 1.35
		}
	],
	"media": [
		{
			"name": "red_scattering",
			"type": "isotropic_scattering",
			"absorption_color": [ 0.9801986733, 0.00609674656, 0.00334596545 ],
			"absorption_at_distance": 1.0,
			"scattering_distance": 0.1
		}
	],
	"materials": [
		{
			"name": "dragon_material",
			"bsdf": "glass",
			"medium": "red_scattering"
		}
	],
	"primitives": [
		{
			"name": "dragon",
			"type": "lmf",
			"file_path": "dragon.lmf",
			"material": "dragon_material"
		}
	]
}

=== RichieSams/lantern/scenes/textured_cube_scene.json
{
	"background_color": [ 0.846, 0.933, 0.949 ],
	"camera": {
		"position": [ 0.0, 10.0, 10.0 ],
		"target": [ 0.0, 0.0, 0.0 ],
		"up": [ 0.0, 1.0, 0.0 ],
		"client_width": 1280,
		"client_height": 720,
		"fov": 0.7853981
	},
	"bsdfs": [
		{
			"name": "gray",
			"type": "lambert",
			"albedo": {
				"type": "constant",
				"value": [ 0.9, 0.9, 0.9 ]
			}
		},
		{
			"name": "left",
			"type": "lambert",
			"albedo": {
				"type": "image",
				"file_path": "left.png"
			}
		},
		{
			"name": "right",
			"type": "lambert",
			"albedo": {
				"type": "image",
				"file_path": "right.png"
			}
		},
		{
			"name": "top",
			"type": "lambert",
			"albedo": {
				"type": "image",
				"file_path": "top.png"
			}
		},
		{
			"name": "bottom",
			"type": "lambert",
			"albedo": {
				"type": "image",
				"file_path": "bottom.png"
			}
		},
		{
			"name": "front",
			"type": "lambert",
			"albedo": {
				"type": "image",
				"file_path": "front.png"
			}
		},
		{
			"name": "back",
			"type": "lambert",
			"albedo": {
				"type": "image",
				"file_path": "back.png"
			}
		},
		{
			"name": "checkerboard",
			"type": "lambert",
			"albedo": {
				"type": "image",
				"file_path": "checkerboard.png"
			}
		},
		{
			"name": "uv",
			"type": "lambert",
			"albedo": {
				"type": "uv"
			}
		}
	],
	"materials": [
		{
			"name": "gray",
			"bsdf": "gray"
		},
		{
			"name": "left",
			"bsdf": "left"
		},
		{
			"name": "right",
			"bsdf": "right"
		},
		{
			"name": "top",
			"bsdf": "top"
		},
		{
			"name": "bottom",
			"bsdf": "bottom"
		},
		{
			"name": "front",
			"bsdf": "front"
		},
		{
			"name": "back",
			"bsdf": "back"
		},
		{
			"name": "checkerboard",
			"bsdf": "checkerboard"
		},
		{
			"name": "uv",
			"bsdf": "uv" 
		}
	],
	"primitives": [
		{
			"name": "left",
			"type": "lmf",
			"file_path": "left.lmf",
			"material": "left"
		},
		{
			"name": "right",
			"type": "lmf",
			"file_path": "right.lmf",
			"material": "right"
		},
		{
			"name": "top",
			"type": "lmf",
			"file_path": "top.lmf",
			"material": "top"
		},
		{
			"name": "bottom",
			"type": "lmf",
			"file_path": "bottom.lmf",
			"material": "bottom"
		},
		{
			"name": "front",
			"type": "lmf",
			"file_path": "front.lmf",
			"material": "front"
		},
		{
			"name": "back",
			"type": "lmf",
			"file_path": "back.lmf",
			"material": "back"
		}
	]
}
